[dev]
172.203.242.3 ansible_user=devOpsUser

[prod]
20.102.96.240 ansible_user=devOpsUser

[webservers]
4.246.180.248 ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
40.114.119.97 ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
20.51.189.60 ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
