[dev]
172.203.242.3 ansible_user=devOpsUser

[prod]
20.102.96.240 ansible_user=devOpsUser
[webservers]
20.121.197.170 ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
52.186.145.204 ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
52.186.156.39  ansible_user=devOpsUser ansible_ssh_pass=Nathcorp!1234
